language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - secure: "jOF/8DrVmhr85p9Cxu2eg+ByYHGHYPdxIthaMbCpoyNpxtdHbjKMeoqSyaNKffqXQ24e6L9lQ6xSZZ45iaQoqg64/04/dnF2JNj6A/czP3iq/apNNOHVCzzqCa1KOkrOv2e01YSxCWzR+Qw22PBxOvj6/0aZeZ94lY8VydJv59IbIG+Y3/HonYQusoljD/90uKZmUMjuAlvybvKFUg58oyF04nGflm9+mQRWpTp8BPtgZXteSZX1u21a/Kg0uykBpE8EZzaBwlMVvS4ZOC+XOP/R0HP5TAJBIPj9vUEuRBMCnihCLQ+zPLeqBaxjBz7gKZPy5hM/qKhiMzluuzEnx6o312SBbqiGokdFGThFFF1YFgGEHSKq467/jpuYKMXVMdy2vh5g30JiGIONNx9xfok3byZGpgAxM9FoDUVM/kL/CkYK8Tq1+bIgimF3ENcsEdWr54QJpuwhj7+jexZUy3PlGhqvPcHV1mTfzNyAxBfAuj+kgHQ4NfZNjLlUCNN7RmMYy+5nuN+Grmb6lMj5hP08bdGdhTo46NBIwdKF/E9LpS5DtlZkQS4N10KtRJWT+fTowaOfm4NZpOx/XVoGIXNQK7/OJuay98m9iWT2biI3d3QJnkZaxHzNu4Byj59ax3reHtLNnwRXOxly6wt+zKZpA3RkEOR4OzPUeaF3wpg="

php:
  - 7.0
  - 5.6
  - hhvm

install:
  - composer require squizlabs/php_codesniffer
  - composer require phpmd/phpmd

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 src/ tests/
  - vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
